language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"
# command to install dependencies
install: "pip install -r requirements.txt"
install: "pip install ."
# command to run tests
script: py.test
