# <=0 ngram means we use word level
# 1+ corresponds to character ngram size (unigrams, bigrams, trigrams)
seed: 43
ngram: 0
max_epochs: 1000
batch_size: 32
dev_batch_size: 256
vocab:
  size: 5000
  threshold: 0
dataset:
  name: CONLL2017_v2_0
  lang: English
model:
  _module: johnny.models
  _classname: GraphParser
  encoder:
    _module: johnny.components
    _classname: SentenceEncoder
    dropout: 0.6
    embedder:
      _module: johnny.components
      _classname: Embedder
      dropout: 0.4
      in_sizes:
      - dunno
      - dunno
      out_sizes:
      - 200
      - 30
    num_layers: 2
    num_units: 200
    use_bilstm: true
  mlp_arc_units: 100
  mlp_lbl_units: 100
  arc_dropout: 0.2
  lbl_dropout: 0.6
  num_labels: dunno
  treeify: none
optimizer:
  grad_clip: 5
  learning_rate: 0.001
preprocess:
  collapse_nums: true
  collapse_triples: true
  lowercase: true
  expand_diacritics: false
  remove_diacritics: false
train_buckets:
  bucket_width: 5
  right_leak: 5
checkpoint:
  patience: 50
  every: 100
