seed: 43
ngram: 1
subword: true
max_epochs: 1000
batch_size: 32
dev_batch_size: 256
vocab:
  size: 200
  threshold: 10
dataset:
  name: CONLL2017_v2_0
  lang: English
model:
  $module: johnny.models
  $classname: GraphParser
  encoder:
    $module: johnny.components
    $classname: SentenceEncoder
    dropout: 0.6
    embedder:
      $module: johnny.components
      $classname: SubwordEmbedder
      dropout: 0.2
      word_encoder:
        $module: johnny.components
        $classname: LSTMWordEncoder
        vocab_size: dunno
        num_units: 200
        num_layers: 1
        rec_dropout: 0.6
        inp_dropout: 0.2
        use_bilstm: true
    num_layers: 2
    num_units: 200
    use_bilstm: true
  mlp_arc_units: 100
  mlp_lbl_units: 100
  arc_dropout: 0.2
  lbl_dropout: 0.6
  num_labels: dunno
  treeify: none
  predict_pos: true
optimizer:
  grad_clip: 5
  learning_rate: 0.001
preprocess:
  collapse_nums: false
  collapse_triples: false
  lowercase: true
  expand_diacritics: true
  remove_diacritics: false
train_buckets:
  bucket_width: 5
  right_leak: 5
checkpoint:
  patience: 50
  every: 100
